### ISSUE TITLE
Problem when using start argument

### ISSUE THREAD

**Issue by fjborquez** [rsaryev/gpt-quiz#1]
Hello, 
I downloaded it and when trying to execute the command, an error appear.

![imagen](https://github.com/rsaryev/gpt-quiz/assets/39710634/cf3f0ba3-cd8f-47b6-8818-951bd75136bd)

https://github.com/rsaryev/gpt-quiz/blob/d50e74ccb4e0ecaa12a2d33745a6251c6e153c50/cmd/start.go#L78

Btw, i'm using a new token and running on windows 10.

**Comment by rsaryev** [comment]
Fixed, update and check please

**Comment by fjborquez** [comment]
Still not works. Now there is an endless spinner with loading message

**Comment by rsaryev** [comment]
Fixed check please last version
